"""added numerical cost to card model

Revision ID: 2e5548fd39ba
Revises: a055f4c7447a
Create Date: 2026-05-19 17:03:48.835755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5548fd39ba'
down_revision: Union[str, Sequence[str], None] = 'a055f4c7447a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('numerical_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'numerical_cost')
    # ### end Alembic commands ###
